#!/bin/bash
# TODO following the example in https://github.com/MediaBrowser/Emby.Build/blob/master/docker-containers/stable/root/var/cache/scripts/emby-server
# cleanup old instanced
# start a named docker container

# reminder: copy env.conf to be used with docker command, but copy from where? have is installed in inst command?
# install -D conf/env.conf /etc/z-container/webmeetings/env.conf

