#!/bin/bash
# TODO following the example in https://github.com/MediaBrowser/Emby.Build/blob/master/docker-containers/stable/root/var/cache/scripts/emby-server
# cleanup old instanced
# start a named docker container

# reminder: use env.conf
#  /etc/z-container/webmeetings/env.conf

